
language: php

git:
    depth: 5

php:
    - 7.1
    - 7.2

install:
    - composer self-update
    - composer install

script:
    - vendor/bin/tale-dev check --report --coverage-php-version=7.1

addons:
    code_climate:
        repo_token: 9c681c931a1a0411dfc5f0ed09cb647976fc142692b5141f444a336c1dadc2ec
